FEEDS = [
 {'id':'njt_bus','operator':'NJ TRANSIT Bus','url':'https://www.njtransit.com/bus_data.zip','authority':'NJ TRANSIT','modes':'bus','consequential':True},
 {'id':'njt_rail','operator':'NJ TRANSIT Rail and Light Rail','url':'https://www.njtransit.com/rail_data.zip','authority':'NJ TRANSIT','modes':'commuter rail; light rail; hybrid rail','consequential':True},
 {'id':'path','operator':'PATH','url':'https://rapid.nationalrtap.org/GTFSFileManagement/UserUploadFiles/14843/PATHGTFS.zip','authority':'FTA National RTAP / PATH','modes':'heavy rail','consequential':True},
 {'id':'patco','operator':'PATCO','url':'https://rapid.nationalrtap.org/GTFSFileManagement/UserUploadFiles/13562/PATCO_GTFS.zip','authority':'FTA National RTAP / PATCO','modes':'heavy rail','consequential':True},
 {'id':'academy','operator':'Academy Lines','url':'https://www.njtransit.com/Academy_bus_data.zip','authority':'FTA GTFS inventory / NJ TRANSIT','modes':'commuter bus','consequential':True},
 {'id':'coachusa','operator':'Coach USA New Jersey services','url':'https://api.prod.coachusa.com/gtfs','authority':'FTA GTFS inventory / Coach USA','modes':'commuter bus','consequential':True},
 {'id':'lakeland','operator':'Lakeland Bus Lines','url':'https://content.njtransit.com/sites/default/files/developers-resources/LakelandBusLines_bus_data.zip','authority':'FTA GTFS inventory / NJ TRANSIT','modes':'commuter bus','consequential':True},
 {'id':'nywaterway_ferry','operator':'NY Waterway Ferry','url':'https://nywaterway.connexionz.net/rtt/public/resource/gtfs.zip','authority':'FTA GTFS inventory / NY Waterway','modes':'ferry','consequential':True},
 {'id':'nywaterway_bus','operator':'NY Waterway Shuttle Bus','url':'https://services.saucontds.com/service-schedule-server/gtfsFeed/749f33f0-b1d7-4be2-b0ea-3f63cf39073e','authority':'FTA GTFS inventory / NY Waterway','modes':'bus','consequential':True},
 {'id':'seastreak','operator':'Seastreak','url':'https://seastreak.com/api/transit/google_transit.zip','authority':'FTA GTFS inventory / Seastreak','modes':'ferry','consequential':True},
 {'id':'boxcar','operator':'Boxcar','url':'https://storage.googleapis.com/storage/v1/b/mdb-latest/o/us-new-jersey-boxcar-gtfs-3105.zip?alt=media','authority':'Mobility Database mirror of official Boxcar feed','modes':'commuter bus','consequential':True},
 {'id':'amtrak','operator':'Amtrak','url':'https://content.amtrak.com/content/gtfs/GTFS.zip','authority':'Amtrak','modes':'intercity rail','consequential':True},
 {'id':'septa','operator':'SEPTA','url':'https://www3.septa.org/developer/gtfs_public.zip','authority':'SEPTA','modes':'regional rail; bus; metro','consequential':True},
 {'id':'mta_si_bus','operator':'MTA Staten Island Bus','url':'https://rrgtfsfeeds.s3.amazonaws.com/gtfs_si.zip','authority':'MTA','modes':'bus','consequential':True},
 {'id':'gloucester','operator':'Gloucester County','url':'https://www.njtransit.com/Gloucester_Co_bus_data.zip','authority':'FTA GTFS inventory / NJ TRANSIT','modes':'bus','consequential':False},
 {'id':'atlantic','operator':'Atlantic County','url':'https://www.njtransit.com/AtlanticCo_bus_data.zip','authority':'FTA GTFS inventory / NJ TRANSIT','modes':'bus','consequential':False},
 {'id':'sjta','operator':'South Jersey Transportation Authority','url':'https://www.njtransit.com/SJTA_bus_data.zip','authority':'FTA GTFS inventory / NJ TRANSIT','modes':'bus','consequential':False},
 {'id':'cumberland','operator':'Cumberland County','url':'https://www.njtransit.com/Cumberland_Co_bus_data.zip','authority':'FTA GTFS inventory / NJ TRANSIT','modes':'bus','consequential':False},
 {'id':'burlington','operator':'Burlington County Shuttles','url':'https://www.njtransit.com/BurlingtonShuttles_bus_data.zip','authority':'FTA GTFS inventory / NJ TRANSIT','modes':'bus','consequential':False},
 {'id':'somerset','operator':'Somerset County','url':'https://www.njtransit.com/SomersetCounty_bus_data.zip','authority':'FTA GTFS inventory / NJ TRANSIT','modes':'bus','consequential':False},
 {'id':'hunterdon','operator':'Hunterdon LINK','url':'https://www.njtransit.com/Hunterdon_Co_bus_data.zip','authority':'FTA GTFS inventory / NJ TRANSIT','modes':'bus','consequential':False},
 {'id':'broadway','operator':'Broadway Bus','url':'https://www.njtransit.com/broadway_bus_data.zip','authority':'FTA GTFS inventory / NJ TRANSIT','modes':'bus','consequential':False},
 {'id':'warren','operator':'Warren County','url':'https://www.njtransit.com/WCT_bus_data.zip','authority':'FTA GTFS inventory / NJ TRANSIT','modes':'bus','consequential':False},
 {'id':'sussex','operator':'Sussex County','url':'https://www.njtransit.com/sussexcounty_bus_data.zip','authority':'FTA GTFS inventory / NJ TRANSIT','modes':'bus','consequential':False},
]
